name: Mystic Mac

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run flask
      run: |
        export FLASK_APP=web_server.py
        export FLASK_DEBUG=1
        python -m flask run --no-debugger --no-reload --port=5002 &
        sleep 10  # Allow flask some time to start up
        ngrok http 5002 &
        sleep 30  # Allow ngrok some time to start up
